### ISSUE TITLE
Add User#display_name functionality

### ISSUE THREAD

**Issue by santouras** [santouras/foosball#24]
right now we have `display_name` as a field, we might be better served by changing the name of this field via an ActiveRecord Migration, and then adding `display_name` functionality that displays either the username or an interpolation of first_name and last_name.

I think `username` might be a good field name, thoughts?

**Comment by boltronics** [comment]
I agree with username, particularly if we ever expect this code to run as an online service where we don't necessarily want or need to expose actual names in some or all contexts.

**Comment by boltronics** [comment]
I guess I might as well take this one, unless someone else wants it.

**Comment by santouras** [comment]
I was thinking about this some more over the weekend, and was wondering if `username` and `display_name` might have different intentions. Perhaps something more like `nickname` would be desirable. Something in line with how [darts players have ludicrous nicknames](http://www.darts501.com/Nicknames.html), this is more what I was thinking that we could do

**Comment by boltronics** [comment]
No worries. And what about login name (if we ever decide to implement logins)? I suppose Nickname probably wouldn't suffice in that case since there is a greater chance of duplicates and it could be more difficult to type. I guess an e-mail address would probably be the login.

I don't have any strong opinions, so whatever you guys think works best.

**Comment by santouras** [comment]
I think `username` would be another thing. Yeah, nicknames shouldn't be login names cause they could have spaces etc and be quite verbose.

Logging in with email is also a really good technique rather than username 👍 

So this functionality would be adding in a method called `display_name` that would return either `nickname` or a concatenation of `first_name` and `last_name`
