### ISSUE TITLE
Add rubocop

### ISSUE THREAD

**Issue by santouras** [santouras/foosball#25]
It will be a good idea to add [Rubocop](https://github.com/bbatsov/rubocop) to our build pipeline early on in the project so we can maintain a consistent codestyle. We can add it to [the travis buildsteps](https://docs.travis-ci.com/user/customizing-the-build/#Customizing-the-Build-Step) pretty easily afterwards.

**Comment by AdamRobertsNZ** [comment]
I'll give this a whirl, if no-one has any objections?

**Comment by boltronics** [comment]
![Objection!!](http://i.kinja-img.com/gawker-media/image/upload/t_large/vix1z65kqge5bxi7yvie.gif)

No, not really. :)
